FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080 \
    ASPNETCORE_ENVIRONMENT=Production

EXPOSE 8080

COPY .docker/backend-publish/ ./

ENTRYPOINT ["dotnet", "Einvoicing.Api.dll"]