version: "3.9"

services:
  ocr-service:
    build: .
    container_name: tuniflow-ocr
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK: "True"
    restart: unless-stopped
